import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AlertTriangle, Chrome, ClipboardCopy, FileSpreadsheet, PauseCircle, Play, Square, TestTube2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { AutomationContext } from "@/components/automation-context";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { copyMavatText, mavatApi, type SettingsData, type WorkflowData } from "@/lib/mavat-api";

export const Route = createFileRoute("/run")({ component: RunPage });
function RunPage(){
  const [settings,setSettings]=useState<SettingsData|null>(null);const [profiles,setProfiles]=useState<WorkflowData["profiles"]>({});const [profileId,setProfileId]=useState("");const [dry,setDry]=useState(false);
  const load=async()=>{const [s,w]=await Promise.all([mavatApi<SettingsData>("/api/settings"),mavatApi<WorkflowData>("/api/workflow")]);setSettings(s);setProfiles(w.profiles);setProfileId(current=>current||Object.keys(w.profiles)[0]||"")};
  useEffect(()=>{load();const timer=setInterval(load,1400);return()=>clearInterval(timer)},[]);const state=settings?.run;const running=["running","manual","stopping"].includes(state?.state||"");const progress=state?.total_rows?Math.round((state.current_row/state.total_rows)*100):0;
  const action=async(name:"start"|"stop"|"continue")=>{try{const body=name==="start"?JSON.stringify({profile_id:profileId,dry_run:dry}):undefined;const result=await mavatApi<{message?:string}>(`/api/run/${name}`,{method:"POST",body});toast.success(result.message||"הפעולה בוצעה");await load()}catch(e){toast.error((e as Error).message)}};
  const openChrome=async()=>{try{await mavatApi("/api/chrome/open",{method:"POST"});toast.success("Chrome נפתח בדף מבא״ת")}catch(e){toast.error((e as Error).message)}};
  return <div className="mx-auto max-w-5xl space-y-8"><AutomationContext/><PageHeader eyebrow="מנוע הרצה" title="הפעלה" description="התחל במצב בדיקה. לאחר אימות השלבים בטל אותו והריץ את התהליך בחלון Chrome של המערכת." actions={<Button variant="outline" onClick={openChrome}><Chrome className="size-4"/>פתח Chrome בלבד</Button>}/>
    <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="font-display text-xl">הגדרות הרצה</CardTitle><CardDescription>בחר מקור נתונים, פרופיל ומצב הפעלה</CardDescription></CardHeader><CardContent className="space-y-4"><div className="rounded-md border p-3"><div className="flex items-center gap-2"><FileSpreadsheet className="size-4 text-accent"/><strong className="text-sm">{settings?.data_file_name||"לא נבחר קובץ נתונים"}</strong></div><p className="mt-1 text-xs text-muted-foreground">את הקובץ ניתן להחליף בדף נתוני לקוחות.</p></div><label className="block space-y-2 text-sm font-medium">פרופיל כניסה<select className="h-10 w-full rounded-md border bg-background px-3" value={profileId} onChange={e=>setProfileId(e.target.value)}>{!Object.keys(profiles).length&&<option value="">לא הוגדר פרופיל</option>}{Object.entries(profiles).map(([id,p])=><option key={id} value={id}>{p.name} · {p.username} {p.has_password?"🔒":"🔑"}</option>)}</select></label><div className={`flex items-center justify-between rounded-md border p-3 ${dry?"border-accent/40 bg-accent/5":"border-emerald-500/40 bg-emerald-500/5"}`}><div><p className="text-sm font-medium">{dry?"מצב בדיקה בלבד":"הרצה אמיתית ב-Chrome"}</p><p className="text-xs text-muted-foreground">{dry?"ללא פתיחת דפדפן וללא שליחת נתונים":"הפעולות יבוצעו בפועל; המערכת תעצור בכל שלב ידני"}</p></div><Switch checked={dry} onCheckedChange={setDry}/></div><div className="flex gap-2"><Button className="flex-1" onClick={()=>action("start")} disabled={running}><Play className="size-4"/>{dry?"התחל בדיקה":"התחל אוטומציה אמיתית"}</Button>{running&&<Button variant="destructive" onClick={()=>action("stop")}><Square className="size-4"/>עצור</Button>}</div></CardContent></Card>
      <Card className={state?.state==="manual"?"border-accent":""}><CardHeader><CardTitle className="flex items-center gap-2 font-display text-xl"><TestTube2 className="size-5 text-accent"/>מצב נוכחי</CardTitle><CardDescription>{state?.message||"מוכן להפעלה"}</CardDescription></CardHeader><CardContent className="space-y-5"><Progress value={progress}/><div className="rounded-md border bg-muted/40 p-4"><p className="font-mono text-xs">מצב: {state?.state||"idle"}</p><p className="mt-2 text-sm">רשומה {state?.current_row||0} מתוך {state?.total_rows||0}</p>{state?.current_step? <p className="mt-1 text-sm">שלב {state.current_step}: {state.current_step_name}</p>:null}</div>{state?.state==="manual"&&<div className="rounded-md border border-accent bg-accent/10 p-4"><div className="flex items-start gap-3"><PauseCircle className="mt-0.5 size-5 text-accent"/><div><strong>נדרשת פעולה ידנית</strong><p className="mt-1 text-sm text-muted-foreground">{state.manual_message}</p></div></div><Button className="mt-4 w-full" onClick={()=>action("continue")}><Play className="size-4"/>ביצעתי — המשך בהרצה</Button></div>}{state?.last_error?.error&&<div className="rounded-md border border-destructive bg-destructive/5 p-4"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 text-destructive"/><div><strong>שלב {state.last_error.step} נכשל: {state.last_error.step_name}</strong><p className="mt-1 text-sm text-destructive">{state.last_error.error}</p><p className="mt-2 break-all font-mono text-xs text-muted-foreground" dir="ltr">{state.last_error.url}</p></div></div><div className="mt-4 flex gap-2"><Button variant="outline" size="sm" onClick={()=>copyMavatText(JSON.stringify(state.last_error,null,2))}><ClipboardCopy className="size-4"/>העתקת פרטי הכשל</Button>{state.last_error.screenshot&&<Button variant="outline" size="sm" asChild><a href="/api/run/error-screenshot" target="_blank">פתיחת צילום הכשל</a></Button>}</div></div>}</CardContent></Card></div>
  </div>;
}
